# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki:1.34
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - /var/www/html/images
      # After initial setup, download LocalSettings.php to the same directory as
      # this yaml and uncomment the following line and use compose to restart
      # the mediawiki service
      - ./app/vendor:/var/www/html/vendor
      - ./app/extensions:/var/www/html/extensions
      - ./app/LocalSettings.php:/var/www/html/LocalSettings.php
      - ./app/.env:/var/www/html/.env
    networks:
      - wiki

  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: wikidb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ${PWD}/docker/local/db:/var/lib/mysql
    networks:
      - wiki

networks:
  wiki: