# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: mediawiki:1.39
    restart: always
    ports:
      - 8080:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - ./app:/var/www/html
    networks:
      - wiki

  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      # @see https://phabricator.wikimedia.org/source/mediawiki/browse/master/includes/DefaultSettings.php
      MYSQL_DATABASE: wikidb
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      #MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./docker/local/db:/var/lib/mysql
    networks:
      - wiki

networks:
  wiki:

volumes:
  images: